# Generated by Django 3.2.8 on 2021-10-13 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autores', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'autores_info',
            },
        ),
        migrations.AddField(
            model_name='obras',
            name='autores',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.autores'),
            preserve_default=False,
        ),
    ]
